#!/bin/bash

  echo "THIS IS EXAMPLE FOR IFELSE STMT "

a=10
b=20

if [ $a -gt $b ]
then
echo "$a is bigger than $b"
else
echo "$b is bigger than $a"
fi


echo "THIS IS EXAMPLE FOR IF ELSE IF"
echo $#
echo $1
echo $2

if [ $# = 0 ]
then
echo "no arguments are passed so please pass the arguments"
elif [ $1 -gt $2 ]
then
echo "$1 is greater than $2"
else
echo "$2 is greater than $1"
fi
~
